fix formatting

diff --git a/bin/git_fresh b/bin/git_fresh
--- a/bin/git_fresh
+++ b/bin/git_fresh
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if ! command -v git >/dev/null 2>&1; then
-	echo "git is required to run fshow"
-	exit 1
+    echo "git is required to run fshow"
+    exit 1
 fi
 
 git fetch --all
